---
- name: Install Pyduino Parallel
  hosts: reactors
  become: yes
  gather_facts: yes
  vars_prompt:
    - name: "GH_TOKEN"
      prompt: "GitHub Token"
      private: true
  vars:
    library_version: master

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - unzip
        - python3
        - python3-pip
        - python3-pandas
        - python3-ipython
      when: ansible_os_family == 'Debian'

    - name: Download repository
      get_url:
        url: https://github.com/fotobiolab-unb/pyduino-parallel/archive/{{ library_version }}.zip
        dest: /home/pi/pyduino-parallel.zip
        headers:
          Authorization: "token {{ GH_TOKEN }}"
      when: ansible_os_family == 'Debian'

    - name: Unzip repository
      block:

        - name: Delete folder if exists
          file:
            remote_src: yes
            path: /home/pi/pyduino-parallel
            state: absent

        - name: Extract and move
          unarchive:
            remote_src: yes
            src: /home/pi/pyduino-parallel.zip
            dest: /home/pi

        - name: Renaming folver
          command: mv /home/pi/pyduino-parallel-{{ library_version }} /home/pi/pyduino-parallel

        - name: Make Writeable
          file:
            path: /home/pi/pyduino-parallel
            mode: 0777
            recurse: yes

    - name: Install Python Libraries
      block:

        - name: Install requirements
          command: pip3 install -r /home/pi/pyduino-parallel/requirements.txt

    - name: Moving unit file to Systemd
      block:

        - name: Delete file if exists
          file:
            remote_src: yes
            path: /etc/systemd/system/pyduino.service
            state: absent
        
        - name: Copy file
          copy:
            remote_src: yes
            src: /home/pi/pyduino-parallel/reactors/pyduino.service
            dest: /etc/systemd/system/pyduino.service

    - name: Deploying and Testing
      block:

        - name: Create Log Folder
          file:
            path: /var/log/pyduino
            state: directory
            mode: 0777

        - name: Daemon Reload
          shell: systemctl daemon-reload

        - name: Enable Service
          shell: systemctl enable pyduino.service

        - name: Start Service
          shell: systemctl start pyduino.service

        - name: Wait for Service
          wait_for:
            port: 5000
            delay: 5
            timeout: 500

        - name: GET port 5000
          uri:
            url: http://localhost:5000
            method: GET
            return_content: yes
          register: result