hyperparameters:
  log_name: "ga_enabled_2" #Log folder name (delete to use the default)
  f_param: DensidadeAtual #Parameter to read as fitness from the reactors
  mutation_probability: 0.01
  resolution: 8 #Number of bits used for each parameter
  elitism: true #Whether or not to use elitism
  ranges:
    branco:
      - 0
      - 10
    full:
      - 0
      - 10
    others:
      - 0
      - 10
system:
  initial_state: "preset_state.csv"
  relevant_parameters:
    - "440"
    - "470"
    - "495"
    - "530"
    - "595"
    - "634"
    - "660"
    - "684"
    - branco
    - full
  irradiance:
    "branco": 10
    "full": 10
    "440": 5.5
    "470": 5.4
    "495": 5.2
    "530": 5.3
    "595": 4.1
    "634": 5.4
    "660": 5.1
    "684": 5.1
  standard_parameters:
  - branco
  - full
  - "440"
  - "470"
  - "495"
  - "530"
  - "595"
  - "634"
  - "660"
  - "684"
  - cor
  - modopainel
  - brilho
  - bomdia
  - boanoite
  - tau
  - step
  - modotemp
  - temp
  - densidade
  - mododil
  - ar
  - ima
  - modoco2
  - co2
  - dtco2
