hyperparameters:
  reset_density: false #Whether or not to use gotod
  log_name: "free_growth_branco_temp_4" #Log folder name (delete to use the default)
  f_param: power #Parameter to read as fitness from the reactors
  density_param: DensidadeAtual #Parameter name for density counts
  mutation_probability: 0.01
  maximize: false
  resolution: 4 #Number of bits used for each parameter
  elitism: true #Whether or not to use elitism
  do_crossover: true #Whether or not to perform crossover when the genetic algorithm is enabled
  rng_seed: 21 #Random seed for genetic algorithm
  ranges:
    branco:
      - 0
      - 30
    full:
      - 0
      - 30
    others:
      - 0
      - 30
slave:
  port: "5000" #Must be a string
  network: "192.168.1.1/24"
system:
  initial_state: "preset_state.csv"
  reboot_wait_time: 5 #Time in seconds to wait after a reboot.
  relevant_parameters:
    - "440"
    - "470"
    - "495"
    - "530"
    - "595"
    - "634"
    - "660"
    - "684"
    - branco
    - full
  irradiance:
    "branco": 10
    "full": 10
    "440": 5
    "470": 5
    "495": 5
    "530": 5
    "595": 4
    "634": 5
    "660": 5
    "684": 5
  standard_parameters:
    branco: int
    full: float
    "440": float
    "470": float
    "495": float
    "530": float
    "595": float
    "634": float
    "660": float
    "684": float
    cor: int
    modopainel: int
    brilho: float
    bomdia: int
    boanoite: int
    tau: int
    step: int
    modotemp: int
    temp: int
    densidade: float
    mododil: int
    ar: int
    ima: int
    modoco2: int
    co2: int
    dtco2: int
dash:
  glob: "./log/free_growth_branco_temp_4/*.csv"
  plot:
    - 
      name: Temperature
      cols:
        Temp:
        SetTemp:
          dash: "dot"
    -
      name: pH
      cols:
        pH:
    -
      name: Density
      cols:
        DensidadeAtual:
    -
      name: Efficiency
      cols:
        efficiency:
    -
      name: GrowthRate
      cols:
        growth_rate:
    -
      name: CO2
      cols:
        CO2:
        SetCO2:
          dash: "dash"
  x_col: 'elapsed_time_hours'
  sep: "\t"
  tail: 128
  display_cols: 3
  theme: cyborg
  subplot_height: 300
  cumulative: false
  update_time: 30000 #In miliseconds
  max_points: 50 #Maximum number of points to display at once
  vspace: 0.1
