name: Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v2
        with:
          token: "${{secrets.TOKEN}}"
      - uses: actions/setup-python@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Install Sphinx
        run: python3 -m pip install -U sphinx myst-parser sphinxcontrib-mermaid furo pylint

      - name: Install dependencies
        working-directory: ./pyduino
        run: python3 -m pip install -r ./requirements.txt

      - name: Run Autodoc
        working-directory: ./doc/docs
        run: sphinx-apidoc -o source ../
      
      - name: Run make
        working-directory: ./doc/docs
        run: make html
      
      - name: Add .nojekyll
        working-directory: ./doc/docs/build/html
        run: touch .nojekyll

      - name: Deploy to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./doc/docs/build/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}