name: Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{secrets.TOKEN}}"
      - uses: actions/setup-python@v2
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Install Sphinx
        run: python3 -m pip install -U sphinx myst-parser sphinxcontrib-mermaid furo

      - name: Install PyLint
        run: python3 -m pip install pylint

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Run Autodoc
        working-directory: ./docs
        run: sphinx-apidoc -o source ../

      - name: Make diagram
        run: |
          pyreverse -s 0 -c Spectra -f SPECIAL spectra.py
          mkdir -p ./docs/build/diagrams
          mv Spectra.dot ./docs/build/diagrams/Spectra.dot
      
      - name: Run make
        working-directory: ./docs
        run: make html

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./docs/build/http/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}