name: sphinx build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Install Sphinx
        run: python3 -m pip install -U sphinx

      - name: Install Markdown Parser
        run: python3 -m pip install --upgrade myst-parser

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Run Autodoc
        working-directory: ./docs
        run: sphinx-apidoc -o source ../
      
      - name: Run make
        working-directory: ./docs
        run: make html